micronaut:
  application:
    name: micronaut_PokeAPI
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/pokemon
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL

liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml
